spring:
  datasource:
    url: jdbc:h2:mem:FluffBotDB
    username: TestDB
    password: TestUser
    driverClassName: org.h2.Driver
    h2:
      console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect